version: "3.4"

services:
  app:
    build:
      context: .
    command: bun run start
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - "1000:80"

volumes:
  node-modules:
